name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd src && javac A3.java
    - name: run
      run: cd src && java A3 30 3 data/S1/process1.txt data/S1/process2.txt data/S1/process3.txt data/S1/process4.txt
